export default {
  extends: ['stylelint-config-standard-vue'],
  plugins: ['stylelint-order'],
  rules: {
    'color-named': [
      'never',
      { message: 'Use hexadecimal color values instead of named colors' },
    ],
    'color-hex-length': 'short',
    'property-no-vendor-prefix': [
      true,
      { ignoreProperties: ['-webkit-text-size-adjust'] },
    ],
    'no-empty-source': null,
    'at-rule-no-unknown': null,
    'custom-property-empty-line-before': null,
    'selector-class-pattern': null,
    'value-keyword-case': null,
    'order/properties-order': [
      [
        {
          groupName: 'positioning',
          properties: ['position', 'top', 'right', 'bottom', 'left', 'z-index'],
        },
        {
          groupName: 'layout',
          properties: [
            'display',
            'grid',
            'grid-area',
            'grid-template',
            'grid-template-columns',
            'grid-template-rows',
            'grid-template-areas',
            'grid-auto-columns',
            'grid-auto-rows',
            'grid-auto-flow',
            'grid-column',
            'grid-row',
            'grid-column-start',
            'grid-column-end',
            'grid-row-start',
            'grid-row-end',
            'grid-gap',
            'grid-column-gap',
            'grid-row-gap',
            'flex',
            'flex-direction',
            'flex-wrap',
            'flex-flow',
            'flex-grow',
            'flex-shrink',
            'flex-basis',
            'justify-content',
            'justify-items',
            'justify-self',
            'align-content',
            'align-items',
            'align-self',
            'place-content',
            'place-items',
            'place-self',
            'order',
            'gap',
            'column-gap',
            'row-gap',
            'contain',
            'will-change',
            'opacity',
            'visibility',
            'overflow',
            'overflow-x',
            'overflow-y',
            'transform',
          ],
        },
        {
          groupName: 'box-model',
          properties: [
            'box-sizing',
            'width',
            'min-width',
            'max-width',
            'height',
            'min-height',
            'max-height',
            'margin',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'margin-left',
            'border',
            'border-top',
            'border-right',
            'border-bottom',
            'border-left',
            'border-width',
            'border-top-width',
            'border-right-width',
            'border-bottom-width',
            'border-left-width',
            'border-style',
            'border-top-style',
            'border-right-style',
            'border-bottom-style',
            'border-left-style',
            'border-color',
            'border-top-color',
            'border-right-color',
            'border-bottom-color',
            'border-left-color',
            'border-radius',
            'border-top-left-radius',
            'border-top-right-radius',
            'border-bottom-right-radius',
            'border-bottom-left-radius',
            'padding',
            'padding-top',
            'padding-right',
            'padding-bottom',
            'padding-left',
          ],
        },
        {
          groupName: 'typography',
          properties: [
            'list-style',
            'list-style-type',
            'list-style-position',
            'list-style-image',
            'line-height',
            'text-align',
            'text-align-last',
            'text-decoration',
            'text-decoration-line',
            'text-decoration-style',
            'text-decoration-color',
            'text-decoration-skip-ink',
            'text-underline-position',
            'text-indent',
            'text-justify',
            'text-overflow',
            'text-shadow',
            'text-transform',
            'text-emphasis',
            'text-emphasis-style',
            'text-emphasis-color',
            'text-emphasis-position',
            'word-spacing',
            'word-break',
            'word-wrap',
            'overflow-wrap',
            'letter-spacing',
            'white-space',
            'font',
            'font-family',
            'font-size',
            'font-weight',
            'font-style',
            'font-variant',
            'font-stretch',
            'font-size-adjust',
            'color',
          ],
        },
        {
          groupName: 'background',
          properties: [
            'background',
            'background-color',
            'background-image',
            'background-repeat',
            'background-attachment',
            'background-position',
            'background-position-x',
            'background-position-y',
            'background-clip',
            'background-origin',
            'background-size',
            'box-shadow',
          ],
        },
        {
          groupName: 'other',
          properties: [
            'appearance',
            'content',
            'cursor',
            'scrollbar-width',
            'scrollbar-color',
            'transition',
            'transition-property',
            'transition-duration',
            'transition-timing-function',
            'transition-delay',
            'animation',
            'animation-name',
            'animation-duration',
            'animation-timing-function',
            'animation-delay',
            'animation-iteration-count',
            'animation-direction',
            'animation-fill-mode',
            'animation-play-state',
          ],
        },
      ],
      { unspecified: 'bottom' },
    ],
  },
}
